# Configuración del sitio
title: "gsanmi1's blog"
description: ""
author: "German Sanmi"
email: your-email@example.com
baseurl: "" # La subruta de tu sitio, ej: /blog
url: "" # La URL base de tu sitio

# Configuración de compilación
markdown: kramdown
theme: minima
permalink: /:year/:month/:day/:title/

# Configuración de Kramdown para LaTeX/MathJax
kramdown:
  math_engine: mathjax  # Let Kramdown preprocess $$ delimiters for MathJax
  syntax_highlighter: rouge
  input: GFM
  hard_wrap: false
  parse_block_html: true
  smart_quotes: ["apos", "apos", "quot", "quot"]

# Configuración de posts
show_excerpts: true

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude archivos del build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# Configuración de colecciones
collections:
  posts:
    output: true
    permalink: /:collection/:year/:month/:day/:title/

# Configuración de navegación
header_pages:
  - zkp.html
  - maths.html
  - past-blogs.html

# Social links (opcional)
github_username: gsanmi1
twitter_username: # tu_usuario
